"""Research domain entity (ENT-009: ResearchReport).

Stores AI-generated research reports for companies.
Reports are versioned and can be regenerated.
"""

from datetime import UTC, datetime

from sqlalchemy import DateTime, ForeignKey, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


def _utcnow() -> datetime:
    return datetime.now(UTC)


class ResearchReport(Base):
    """An AI-generated research report for a company.

    Reports are generated on demand and cached. The source_type
    indicates what triggered the generation (manual, auto, scheduled).
    AI analysis sections are stored as versioned JSON.
    """

    __tablename__ = "research_reports"

    id: Mapped[str] = mapped_column(String(24), primary_key=True)
    user_id: Mapped[str] = mapped_column(
        String(24),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    company_id: Mapped[str] = mapped_column(
        String(24),
        ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    source_type: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="manual",
    )  # manual, auto, scheduled

    # Executive summary generated by AI
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Structured analysis sections: { "version": 1, "data": { ... } }
    analysis: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    # The prompt registry key used for generation
    prompt_key: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Generation metadata
    model_used: Mapped[str | None] = mapped_column(String(50), nullable=True)
    tokens_used: Mapped[int] = mapped_column(default=0, nullable=False)
    generation_time_ms: Mapped[int] = mapped_column(default=0, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
    )