import type { MockResponseResolver } from '@/services/ai/providers/mockAIProvider'
import type {
  CoachingTip,
  LessonRecommendation,
  LearningReflection,
} from '@/types/aiLearning'

// ─── Mock AI Learning Responses ───
// All outputs use educational language — no evaluation labels,
// no financial advice phrasing.
// Every response includes provenance metadata.

const coachingTip: CoachingTip = {
  lessonId: 'mod-1-les-2',
  lessonTitle: 'Understanding Market Orders and Limit Orders',
  tip:
    'When you placed your recent trades, you used market orders, which execute immediately at the best available price. In contrast, a **limit order** lets you specify the maximum price you are willing to pay (when buying) or the minimum price you will accept (when selling). Understanding the difference is important because:\n\n- **Market orders** prioritise speed of execution — your order fills quickly, but the exact price may vary slightly from what you see on screen.\n- **Limit orders** prioritise price control — you set the price, but the order may not fill if the market never reaches your specified price.\n\nIn a learning context, try placing a limit order on your next trade to see how it behaves differently from the market orders you have used so far.',
  connectionToPortfolio:
    'Your transaction history shows market orders were used for all recent trades. Experimenting with limit orders would provide practical experience with a different order type and help you understand when each approach might be more appropriate.',
  provenance: {
    reason:
      'This coaching tip was generated based on the trading patterns observed in your portfolio, connecting your actual activity to the lesson on order types.',
    dataSources: [
      'Current lesson progress (Module 1: Getting Started)',
      'Recent transaction history and order types used',
    ],
  },
}

const lessonRecommendation: LessonRecommendation = {
  recommendedLessonId: 'mod-2-les-1',
  recommendedLessonTitle: 'Understanding Financial Statements',
  reason:
    'Based on your trading activity, you have been actively investing in companies across IT and banking sectors. Understanding financial statements — income statements, balance sheets, and cash flow statements — would help you evaluate the companies you are trading with more context. For example, knowing how to read a bank\'s balance sheet helps explain why metrics like Net Interest Margin and CASA ratio (mentioned in research reports) matter.',
  priority: 'high',
  provenance: {
    reason:
      'This lesson recommendation was generated because your trading activity involves sectors where financial statement analysis is directly relevant, making this the most educationally valuable next step.',
    dataSources: [
      'Current learning progress',
      'Portfolio sector allocation (IT and Banking)',
      'Lesson curriculum structure',
    ],
  },
}

const learningReflection: LearningReflection = {
  observations: [
    'Your trading activity shows a preference for large-cap, well-established companies. This is a common starting point — these companies tend to have more available research and lower volatility, making them suitable for building foundational understanding.',
    'Your trades have been distributed across IT and financial services sectors. This pattern suggests an interest in understanding different sectors of the Indian economy.',
    'The timing between trades suggests a measured approach — you are not making rapid-fire trades but rather taking time between decisions.',
  ],
  strengths: [
    'Selecting well-established, liquid companies demonstrates an understanding of the importance of company quality and market accessibility.',
    'Distributing trades across sectors shows awareness that different sectors respond to different economic factors.',
  ],
  areasForImprovement: [
    'Understanding order types (market vs. limit) could add more tools to your trading approach.',
    'Financial statement analysis skills would complement your current company selection process with deeper fundamental context.',
    'Learning about position sizing concepts could help develop a more structured approach to allocating capital across trades.',
  ],
  connectedLessons: [
    'Understanding Market Orders and Limit Orders — connects directly to your trading execution method',
    'Understanding Financial Statements — relevant to evaluating the companies you hold',
    'Risk Management Basics — relevant to thinking about how much capital to allocate per trade',
  ],
  provenance: {
    reason:
      'This learning reflection was generated by analysing your trading decisions and connecting them to relevant lesson concepts, helping you see the practical application of what you are learning.',
    dataSources: [
      'Complete transaction history',
      'Current learning module progress',
      'Lesson curriculum and concept mapping',
    ],
  },
}

/** Mock resolver for learning AI endpoints */
export function createLearningMockResolver(): MockResponseResolver {
  return (_endpoint: string, _payload: unknown) => {
    if (_endpoint.includes('coaching-tip')) {
      return coachingTip
    }

    if (_endpoint.includes('lesson-recommendation')) {
      return lessonRecommendation
    }

    if (_endpoint.includes('learning-reflection')) {
      return learningReflection
    }

    return { _mock: true, endpoint: _endpoint }
  }
}