"""Company seed data.

This is the single source of truth for all 10 seed companies.
Every ID, symbol, sector, price, and financial value MUST match
the frontend types and mock data exactly.

Reference: frontend/src/data/companies.ts
Reference: frontend/src/types/company.ts
"""

from app.modules.market.models import Company

# ─── Company seed data ───
# EXACT parity with frontend/src/data/companies.ts
# DO NOT change IDs or symbols without updating frontend types.

COMPANIES: list[dict] = [
    {
        "id": "cmp-001",
        "name": "Reliance Industries Ltd",
        "symbol": "RELIANCE",
        "sector": "Energy",
        "industry": "Oil & Gas / Conglomerate",
        "exchange": "NSE",
        "market_cap": "25,12,340 Cr",
        "current_price": 2945.30,
        "previous_close": 2920.15,
        "day_change": 25.15,
        "day_change_percent": 0.86,
        "volume": 8432150,
        "pe": 28.40,
        "pb": 2.90,
        "dividend_yield": 0.32,
        "week52_high": 3102.50,
        "week52_low": 2220.10,
        "description": "Reliance Industries Limited is an Indian multinational conglomerate headquartered in Mumbai. It operates in petrochemicals, refining, oil and gas exploration, retail, telecommunications, and digital services.",
        "website": "ril.com",
        "founded_year": 1966,
        "employees": 389000,
        "revenue": 1054320,
        "net_profit": 79560,
        "debt": 215000,
        "cash_flow": 94500,
        "roe": 10.20,
        "roa": 6.80,
        "promotor_holding": 50.32,
        "institutional_holding": 24.15,
        "public_holding": 25.53,
    },
    {
        "id": "cmp-002",
        "name": "Tata Consultancy Services Ltd",
        "symbol": "TCS",
        "sector": "IT",
        "industry": "Information Technology",
        "exchange": "NSE",
        "market_cap": "14,85,210 Cr",
        "current_price": 4056.70,
        "previous_close": 4098.25,
        "day_change": -41.55,
        "day_change_percent": -1.01,
        "volume": 3210480,
        "pe": 32.10,
        "pb": 13.80,
        "dividend_yield": 1.28,
        "week52_high": 4434.80,
        "week52_low": 3612.30,
        "description": "Tata Consultancy Services is a global IT services, consulting, and business solutions organization. It is the largest IT company in India by market capitalization and a subsidiary of the Tata Group.",
        "website": "tcs.com",
        "founded_year": 1968,
        "employees": 601000,
        "revenue": 245000,
        "net_profit": 46230,
        "debt": 0,
        "cash_flow": 48900,
        "roe": 47.50,
        "roa": 22.10,
        "promotor_holding": 72.33,
        "institutional_holding": 15.82,
        "public_holding": 11.85,
    },
    {
        "id": "cmp-003",
        "name": "HDFC Bank Ltd",
        "symbol": "HDFCBANK",
        "sector": "Banking",
        "industry": "Banking / Financial Services",
        "exchange": "NSE",
        "market_cap": "13,42,890 Cr",
        "current_price": 1728.45,
        "previous_close": 1715.80,
        "day_change": 12.65,
        "day_change_percent": 0.74,
        "volume": 12543600,
        "pe": 21.30,
        "pb": 3.40,
        "dividend_yield": 1.10,
        "week52_high": 1860.20,
        "week52_low": 1365.40,
        "description": "HDFC Bank is an Indian banking and financial services company headquartered in Mumbai. It is the largest private sector bank in India by assets and market capitalization.",
        "website": "hdfcbank.com",
        "founded_year": 1994,
        "employees": 172000,
        "revenue": 287650,
        "net_profit": 52340,
        "debt": 0,
        "cash_flow": 55600,
        "roe": 16.40,
        "roa": 1.90,
        "promotor_holding": 26.14,
        "institutional_holding": 43.21,
        "public_holding": 30.65,
    },
    {
        "id": "cmp-004",
        "name": "Infosys Ltd",
        "symbol": "INFY",
        "sector": "IT",
        "industry": "Information Technology",
        "exchange": "NSE",
        "market_cap": "7,62,340 Cr",
        "current_price": 1872.60,
        "previous_close": 1890.10,
        "day_change": -17.50,
        "day_change_percent": -0.93,
        "volume": 5432100,
        "pe": 27.80,
        "pb": 8.20,
        "dividend_yield": 2.15,
        "week52_high": 2045.30,
        "week52_low": 1455.60,
        "description": "Infosys is an Indian multinational information technology company that provides business consulting, information technology, and outsourcing services. It is the second-largest Indian IT company after TCS.",
        "website": "infosys.com",
        "founded_year": 1981,
        "employees": 312000,
        "revenue": 164530,
        "net_profit": 27120,
        "debt": 0,
        "cash_flow": 28900,
        "roe": 30.10,
        "roa": 17.80,
        "promotor_holding": 14.94,
        "institutional_holding": 47.32,
        "public_holding": 37.74,
    },
    {
        "id": "cmp-005",
        "name": "ITC Ltd",
        "symbol": "ITC",
        "sector": "FMCG",
        "industry": "FMCG / Hotels / Paper",
        "exchange": "NSE",
        "market_cap": "5,89,120 Cr",
        "current_price": 475.85,
        "previous_close": 471.20,
        "day_change": 4.65,
        "day_change_percent": 0.99,
        "volume": 9876540,
        "pe": 26.50,
        "pb": 7.90,
        "dividend_yield": 3.15,
        "week52_high": 498.70,
        "week52_low": 387.20,
        "description": "ITC Limited is an Indian multinational conglomerate company headquartered in Kolkata. Its businesses include cigarettes, FMCG, hotels, paperboards, specialty papers, and packaging.",
        "website": "itcportal.com",
        "founded_year": 1910,
        "employees": 36500,
        "revenue": 70210,
        "net_profit": 20150,
        "debt": 0,
        "cash_flow": 24300,
        "roe": 25.80,
        "roa": 13.60,
        "promotor_holding": 0.0,
        "institutional_holding": 42.15,
        "public_holding": 57.85,
    },
    {
        "id": "cmp-006",
        "name": "Maruti Suzuki India Ltd",
        "symbol": "MARUTI",
        "sector": "Automobile",
        "industry": "Automobile / Passenger Vehicles",
        "exchange": "NSE",
        "market_cap": "4,12,560 Cr",
        "current_price": 12645.80,
        "previous_close": 12780.50,
        "day_change": -134.70,
        "day_change_percent": -1.05,
        "volume": 1823400,
        "pe": 30.20,
        "pb": 5.60,
        "dividend_yield": 0.86,
        "week52_high": 13950.00,
        "week52_low": 9850.40,
        "description": "Maruti Suzuki India Limited is an Indian automobile manufacturer headquartered in New Delhi. It is a subsidiary of the Japanese company Suzuki Motor Corporation and the largest car manufacturer in India.",
        "website": "marutisuzuki.com",
        "founded_year": 1981,
        "employees": 15800,
        "revenue": 132800,
        "net_profit": 10820,
        "debt": 4560,
        "cash_flow": 12800,
        "roe": 15.30,
        "roa": 9.20,
        "promotor_holding": 56.48,
        "institutional_holding": 18.94,
        "public_holding": 24.58,
    },
    {
        "id": "cmp-007",
        "name": "Sun Pharmaceutical Industries Ltd",
        "symbol": "SUNPHARMA",
        "sector": "Pharma",
        "industry": "Pharmaceuticals",
        "exchange": "NSE",
        "market_cap": "4,45,780 Cr",
        "current_price": 1823.40,
        "previous_close": 1810.75,
        "day_change": 12.65,
        "day_change_percent": 0.70,
        "volume": 4123500,
        "pe": 38.50,
        "pb": 6.30,
        "dividend_yield": 0.42,
        "week52_high": 1962.10,
        "week52_low": 1205.30,
        "description": "Sun Pharmaceutical Industries is an Indian multinational pharmaceutical company headquartered in Mumbai. It is the fourth-largest generic pharmaceutical company in the world by revenue.",
        "website": "sunpharma.com",
        "founded_year": 1983,
        "employees": 41000,
        "revenue": 54230,
        "net_profit": 11850,
        "debt": 12400,
        "cash_flow": 14200,
        "roe": 14.20,
        "roa": 7.50,
        "promotor_holding": 54.66,
        "institutional_holding": 20.15,
        "public_holding": 25.19,
    },
    {
        "id": "cmp-008",
        "name": "ICICI Bank Ltd",
        "symbol": "ICICIBANK",
        "sector": "Banking",
        "industry": "Banking / Financial Services",
        "exchange": "NSE",
        "market_cap": "9,12,450 Cr",
        "current_price": 1289.30,
        "previous_close": 1272.60,
        "day_change": 16.70,
        "day_change_percent": 1.31,
        "volume": 15342800,
        "pe": 18.90,
        "pb": 3.10,
        "dividend_yield": 0.95,
        "week52_high": 1354.80,
        "week52_low": 985.60,
        "description": "ICICI Bank is an Indian multinational bank and financial services company headquartered in Mumbai. It is the second-largest private sector bank in India by assets and market capitalization.",
        "website": "icicibank.com",
        "founded_year": 1994,
        "employees": 95000,
        "revenue": 212450,
        "net_profit": 44230,
        "debt": 0,
        "cash_flow": 48700,
        "roe": 17.80,
        "roa": 1.90,
        "promotor_holding": 0.0,
        "institutional_holding": 52.34,
        "public_holding": 47.66,
    },
    {
        "id": "cmp-009",
        "name": "Hindustan Petroleum Corp Ltd",
        "symbol": "HINDPETRO",
        "sector": "Energy",
        "industry": "Oil & Gas / Refining",
        "exchange": "NSE",
        "market_cap": "1,32,890 Cr",
        "current_price": 542.70,
        "previous_close": 538.15,
        "day_change": 4.55,
        "day_change_percent": 0.85,
        "volume": 6234500,
        "pe": 8.40,
        "pb": 1.80,
        "dividend_yield": 3.82,
        "week52_high": 625.40,
        "week52_low": 388.90,
        "description": "Hindustan Petroleum Corporation Limited is an Indian public sector oil and gas company headquartered in Mumbai. It is a Mega CPSE with Maharatna status.",
        "website": "hindustanpetroleum.com",
        "founded_year": 1974,
        "employees": 11200,
        "revenue": 342100,
        "net_profit": 8540,
        "debt": 28900,
        "cash_flow": 9200,
        "roe": 21.30,
        "roa": 5.40,
        "promotor_holding": 51.11,
        "institutional_holding": 18.23,
        "public_holding": 30.66,
    },
    {
        "id": "cmp-010",
        "name": "Tata Motors Ltd",
        "symbol": "TATAMOTORS",
        "sector": "Automobile",
        "industry": "Automobile / Commercial Vehicles",
        "exchange": "NSE",
        "market_cap": "3,45,210 Cr",
        "current_price": 958.25,
        "previous_close": 967.40,
        "day_change": -9.15,
        "day_change_percent": -0.95,
        "volume": 11234500,
        "pe": 12.60,
        "pb": 2.40,
        "dividend_yield": 0.52,
        "week52_high": 1178.30,
        "week52_low": 640.50,
        "description": "Tata Motors Limited is an Indian multinational automotive manufacturing company headquartered in Mumbai. It is a part of the Tata Group and manufactures passenger cars, trucks, vans, and coaches.",
        "website": "tatamotors.com",
        "founded_year": 1945,
        "employees": 82600,
        "revenue": 440000,
        "net_profit": 28960,
        "debt": 98400,
        "cash_flow": 32100,
        "roe": 22.40,
        "roa": 5.80,
        "promotor_holding": 46.39,
        "institutional_holding": 20.84,
        "public_holding": 32.77,
    },
]


async def seed_companies(session) -> int:
    """Insert company seed data into the database.

    Args:
        session: An async SQLAlchemy session (caller manages commit).

    Returns:
        Number of companies inserted.
    """
    from sqlalchemy import func, select

    count_result = await session.execute(select(func.count()).select_from(Company))
    count = count_result.scalar()

    if count and count > 0:
        print(f"  Companies: {count} already exist, skipping.")
        return 0

    for c_data in COMPANIES:
        company = Company(**c_data)
        session.add(company)

    await session.flush()
    print(f"  Companies: inserted {len(COMPANIES)} records.")
    return len(COMPANIES)
